name: workflow for issue 
on:
  issues:
    types:
      - opened
      - reopened 
jobs:
  FirstJob:
    runs-on: ubuntu-latest
    env:
      issue_number: ${{github.event.issue.number}}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - run: gh issue edit $issue_number --add-label bug
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{github.repository}}
