name: test container on github ctions 
on:
  workflow_dispatch
jobs:
  Job1:
    runs-on: ubuntu-latest
    container:
      image: nginx
      ports:
       - 80:8000
      
      options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
       
    steps:
      - name: check out the code 
        uses: actions/checkout@v4.2.2
      - name: list the current directory
        run: cp index.php /usr/share/nginx/html
      - name: test the resulte
        run:  service nginx start #curl  http://localhost
      - run: service nginx status
      - run : curl  http://localhost
