name: test container on github ctions 
on:
  workflow_dispatch
jobs:
  Job1:
    runs-on: ubuntu-latest
    container:
      image: php:8.5.0alpha1-zts-bullseye
      ports:
        - 80:8000
      options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4.2.2
     # - run : docker build -t php_image .
     # - run: docker run --rm --name test php_image 
      - run : php index.php
      - run: echo "YESSSSSSSSSSSSSSS"
        if: ${{ success() }}
       
       
