name: test container on github ctions 
on:
  workflow_dispatch
jobs:
  Job1:
    runs-on: ubuntu-latest
    container:
      image: php:8.5.0alpha1-zts-bullseye
      ports:
        - 80:8000
      options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
   
    services:
      # Label used to access the service container
      mysql:
        # Docker Hub image
        image: mysql:oraclelinux9
        env:
          MYSQL_ROOT_PASSWORD: "khalaf"
          MYSQL_USER: root
          MYSQL_DATABASE: test_db
    steps:
      - name: checkout the code.
        uses: actions/checkout@v4.2.2
      -  name: run php code 
         run: php index.php
      - name: test database
        run: php test.php

      - name: check resulte
        if: ${{success()}}
        run: echo "All test done "
