name: test container on github ctions 
on:
  workflow_dispatch
jobs:
  Job1:
    runs-on: ubuntu-latest      
    steps:
      - uses: actions/checkout@v4.2.2
      - run : docker build -t php_image .
      - run: docker run --rm --name test php_image 
    
      
