name: push image to docker hub account 
on:
  workflow_dispatch
jobs:
  push_docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - run: |
         docker build -t git_hub_image .
         docker tag git_hub_image ${{secrets.DOCKER_NAME}}/test_repo:2.1
         docker login -u ${{secrets.DOCKER_NAME}} -p ${{secrets.DOCKER_PASSWORD}}
         docker push ${{secrets.DOCKER_NAME}}/test_repo:2.1
  
